ABOH-18: Create Login page
valeryia-rusakova/a-bit-of-habit-react pull request #1
Opened 2021-09-20 22:34 UTC by valeryia-rusakova

2021-09-21 09:59 UTC, veranika-zakharchenia commented on react-project/src/components/Login.js
> +    background-color: #EDA794;
let's move all constants to the separate file

2021-09-21 10:00 UTC, veranika-zakharchenia commented on react-project/src/components/Login.js
> +    position: absolute;
is this the only solution? could we avoid this somehow?

2021-09-21 10:04 UTC, veranika-zakharchenia commented on react-project/src/components/Login.js
> +                    <SpanWrapper><AccountCircle style={{ color: '#F8F9F9'}}/></SpanWrapper>
try not to use styles within props

2021-09-21 10:05 UTC, veranika-zakharchenia requested changes
.

2021-09-21 10:44 UTC, valeryia-rusakova commented on react-project/src/components/Login.js
> +    position: absolute;
what do you mean exactly?

2021-09-21 12:06 UTC, veranika-zakharchenia commented on react-project/src/components/Login.js
> +    position: absolute;
the usage of `position: absolute` is not the best solution because it can cause some problems in the future, so we should use this construction only in the edge case

2021-09-23 11:04 UTC, veranika-zakharchenia approved these changes

2021-09-23 11:10 UTC, merged